global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "aztibase-validators"
    static_configs:
      - targets:
          - "validator1:9944"
          - "validator2:9944"
          - "validator3:9944"
        labels:
          network: "testnet"
    metrics_path: "/metrics"
    scheme: "http"
