[package]
name = "aztibase-network"
description = "P2P networking layer (libp2p, gossipsub, Kademlia DHT) for Aztibase Network"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
webrtc = ["libp2p-webrtc"]

[dependencies]
aztibase-core = { workspace = true }
tokio = { workspace = true }
libp2p = { workspace = true }
libp2p-webrtc = { version = "0.9.0-alpha.1", features = ["tokio"], optional = true }
tracing = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
postcard = { workspace = true }
prost = { workspace = true }
bytes = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
redb = { workspace = true }
