[package]
name = "aztibase-network"
description = "P2P networking layer (libp2p, gossipsub, Kademlia DHT) for Aztibase Network"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
aztibase-core = { workspace = true }
tokio = { workspace = true }
libp2p = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
prost = { workspace = true }
bytes = { workspace = true }
anyhow = { workspace = true }
futures = { workspace = true }
