[package]
name = "aztibase-rpc"
description = "JSON-RPC server for Aztibase Network"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
aztibase-core = { workspace = true }
aztibase-consensus = { workspace = true }
aztibase-execution = { workspace = true }
aztibase-storage = { workspace = true }
postcard = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
axum = { workspace = true }
hex = { workspace = true }
futures = { workspace = true }
prometheus-client = { workspace = true }

[dev-dependencies]
tower = "0.5"
tokio-tungstenite = "0.26"
